[package]
name = "WarOfTheWorlds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ratatui = "0.23.0"
serde = "1.0.188"
termcolor = "1.2.0"
